//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssigned.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssignProjectEntities : DbContext
    {
        public AssignProjectEntities()
            : base("name=AssignProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreateDeveloper> CreateDevelopers { get; set; }
        public virtual DbSet<CreateProject> CreateProjects { get; set; }
        public virtual DbSet<DeveloperWorkProgress> DeveloperWorkProgresses { get; set; }
        public virtual DbSet<NewModule> NewModules { get; set; }
        public virtual DbSet<ProjectFeedback> ProjectFeedbacks { get; set; }
    }
}
